### ISSUE TITLE
(Enhancement)Add a Home button to access to the homepage quickly

### ISSUE THREAD

**Issue by Richard38907** [Arturo254/InnerTune#9]
Add a home button to go back to the home page of the app directly instead of pressing back button to many times after a lot of songs searches
![IMG_20240411_160744.png](https://github.com/Arturo254/InnerTune/assets/148692265/e1e9ab90-e910-4764-9319-3dc50447c4ac)

Thank you for your fork, it is a real hot fix from the original release👌!

**Comment by Arturo254** [comment]
I'll keep that in mind for the next update 
Do you have any idea where I can put the button
I'm talking about the place 

Thank you for your comment ❤️

**Comment by Richard38907** [comment]
There
![Screenshot_20240411-185907_InnerTune.png](https://github.com/Arturo254/InnerTune/assets/148692265/28713e63-459b-4535-946a-f5088621669d)

It's the better place for me👌.
_____
 A floating button in the bottom like this can be hit by mistake (second photo)it's not a good idea
![Screenshot_20240411-190330_InnerTune.png](https://github.com/Arturo254/InnerTune/assets/148692265/d81f1e0b-1f5a-4be9-9e56-d60812453fdd)

**Comment by Richard38907** [comment]
Or you can simply let the tab bar visible on all pages of the app like Spotify (for second option). It's always good🙂.

**Comment by Arturo254** [comment]
![image](https://github.com/Arturo254/InnerTune/assets/87346871/f36831d6-c7fb-4774-89f9-cc014880336a)
I just added the home button, I did not put it in the place you proposed due to space issues in the bar
now I upload the apk (zip)- {unzip}  *(create a backup)*
[app-foss-release.zip](https://github.com/Arturo254/InnerTune/files/14952667/app-foss-release.zip)
